### ISSUE TITLE
Suggest bump the base image 'ubuntu' to latest trusty-20150806

### ISSUE THREAD

**Issue by vancepym** [sameersbn/docker-ubuntu#10]
The latest official ubuntu docker image has released as trusty-20150806, please keep up with the latest asap. Thanks.

**Comment by vancepym** [comment]
Dear sameersbn, now you can bump version to trusty-20150814, see https://hub.docker.com/_/ubuntu/, thanks.

**Comment by sameersbn** [comment]
Done!
