### ISSUE TITLE
change source list of ubuntu

### ISSUE THREAD

**Issue by fevxie** [sameersbn/docker-ubuntu#13]
hi,  @sameersbn :

    I want to change the source list of ubuntu repository,Shall I do it using your Ubuntu image? 

Thanks.

**Comment by sameersbn** [comment]
Hi @fevxie. Sorry for the lateness of my response.
In general the `sources.list` file should be updated in your own `Dockerfile`. For an example take a look at https://github.com/sameersbn/docker-bind/blob/master/Dockerfile#L11.

Closing the issue, please re-open if you need further assitance
