### ISSUE TITLE
Use runit-based image instead of (plain) Ubuntu image

### ISSUE THREAD

**Issue by fbender** [sameersbn/docker-ubuntu#4]
Hi there, 

since the official Ubuntu image has some issues with running inside Docker, I'd like to see your superb Dockerfiles be based on phusion/baseimage-docker instead. They explain why this has benefits on the project page: http://phusion.github.io/baseimage-docker/

Thank you for your consideration!

**Comment by sameersbn** [comment]
@fbender closing.. too much work, too little benefits (it at all)
