### ISSUE TITLE
Add gosu install

### ISSUE THREAD

**Issue by mizunashi-mana** [sameersbn/docker-ubuntu#9]
Your docker images really helped me and I learn a lot. thx.

Wondering, I used `sameersbn/docker-redis` image.  Its start shell is using `gosu`.  But, its base image, this ubuntu image, is seemed by me not to install `gosu`.  And, the image pulling by `docker pull sameersbn/ubuntu:14.04.20150603`  included `gosu`.

Although maybe my less knowledge caused, I think a better way is to add run step installing `gosu` on Dockerfile.  And, if I miss, please tell me about the amazing happening.

**Comment by sameersbn** [comment]
@mizunashi-mana Please update the docker-redis image or source. The gosu command is not being used by my images anymore. I switched to using the `start-stop-daemon` command instead.

**Comment by mizunashi-mana** [comment]
Oh, i see. Thx
